from enum import StrEnum


class FeatureSupportInLatestVersion(StrEnum):
    SUPPORTED = "SUPPORTED"
    SUPPORTED_WITH_LICENSE_UPGRADE = "SUPPORTED_WITH_LICENSE_UPGRADE"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    NON_DEFAULT_PROVIDER = "NON_DEFAULT_PROVIDER"
