name: ❓ Question
description: Ask a question about LocalStack
title: "question: <title>"
labels: [question]
body:
- type: markdown
  attributes:
    value: |
      If you need real-time help, please join our [community Slack](https://localstack-community.slack.com).
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the question you have, or your question is answered in the [Localstack Documentation](https://localstack.cloud/docs/).
    options:
    - label: I have searched the existing issues and read the documentation
      required: true
- type: textarea
  attributes:
    label: Question
    description: Please ask your question here
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the question you have!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
