# LocalStack Resource Provider Scaffolding v2
from __future__ import annotations

from pathlib import Path
from typing import Optional, Type, TypedDict

import localstack.services.cloudformation.provider_utils as util
from localstack.services.cloudformation.resource_provider import (
    CloudFormationResourceProviderPlugin,
    OperationStatus,
    ProgressEvent,
    ResourceProvider,
    ResourceRequest,
)


class IAMGroupProperties(TypedDict):
    Arn: Optional[str]
    GroupName: Optional[str]
    Id: Optional[str]
    ManagedPolicyArns: Optional[list[str]]
    Path: Optional[str]
    Policies: Optional[list[Policy]]


class Policy(TypedDict):
    PolicyDocument: Optional[dict]
    PolicyName: Optional[str]


REPEATED_INVOCATION = "repeated_invocation"


class IAMGroupProvider(ResourceProvider[IAMGroupProperties]):

    TYPE = "AWS::IAM::Group"  # Autogenerated. Don't change
    SCHEMA = util.get_schema_path(Path(__file__))  # Autogenerated. Don't change

    def create(
        self,
        request: ResourceRequest[IAMGroupProperties],
    ) -> ProgressEvent[IAMGroupProperties]:
        """
        Create a new resource.

        Primary identifier fields:
          - /properties/Id



        Create-only properties:
          - /properties/GroupName

        Read-only properties:
          - /properties/Arn
          - /properties/Id



        """
        model = request.desired_state

        # TODO: validations

        if not request.custom_context.get(REPEATED_INVOCATION):
            # this is the first time this callback is invoked
            # TODO: defaults
            # TODO: idempotency
            # TODO: actually create the resource
            request.custom_context[REPEATED_INVOCATION] = True
            return ProgressEvent(
                status=OperationStatus.IN_PROGRESS,
                resource_model=model,
                custom_context=request.custom_context,
            )

        # TODO: check the status of the resource
        # - if finished, update the model with all fields and return success event:
        #   return ProgressEvent(status=OperationStatus.SUCCESS, resource_model=model)
        # - else
        #   return ProgressEvent(status=OperationStatus.IN_PROGRESS, resource_model=model)

        raise NotImplementedError

    def read(
        self,
        request: ResourceRequest[IAMGroupProperties],
    ) -> ProgressEvent[IAMGroupProperties]:
        """
        Fetch resource information


        """
        raise NotImplementedError

    def delete(
        self,
        request: ResourceRequest[IAMGroupProperties],
    ) -> ProgressEvent[IAMGroupProperties]:
        """
        Delete a resource


        """
        raise NotImplementedError

    def update(
        self,
        request: ResourceRequest[IAMGroupProperties],
    ) -> ProgressEvent[IAMGroupProperties]:
        """
        Update a resource


        """
        raise NotImplementedError


class IAMGroupProviderPlugin(CloudFormationResourceProviderPlugin):
    name = "AWS::IAM::Group"

    def __init__(self):
        self.factory: Optional[Type[ResourceProvider]] = None

    def load(self):
        self.factory = IAMGroupProvider
