Parameters:
  QuotaLimit:
    Type: Number
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: RestApi
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId:
            Ref: Stage
      Quota:
        Limit:
          Ref: QuotaLimit

Outputs:
    UsagePlanId:
        Value: !Ref UsagePlan