name: 'Setup Test Environment'
description: 'Composite action which combines all steps necessary to setup the runner for test execution'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
        cache: 'pip'
        cache-dependency-path: 'requirements-typehint.txt'

    - name: Install Community Dependencies
      shell: bash
      run: make install-dev-types

    - name: Setup environment
      shell: bash
      run: |
        make install
        mkdir -p target/reports
        mkdir -p target/coverage
