name: 'Setup Test Environment Against Docker'
description: 'Composite action which combines all steps necessary to setup the runner for local test execution against docker container'
inputs:
  platform:
    required: true
    description: Platform
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # setuptools_scm requires the git history (at least until the last tag) to determine the version
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'

    - name: Download Docker Image
      uses: actions/download-artifact@v4
      with:
        name: localstack-docker-image-${{ inputs.platform }}

    - name: Install docker helper dependencies
      shell: bash
      run: pip install --upgrade setuptools setuptools_scm

    - name: Load Docker Image
      shell: bash
      run: bin/docker-helper.sh load
