apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "localstack.name" . }}
    helm.sh/chart: {{ include "localstack.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "localstack.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "localstack.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.localstack.port }}
              protocol: TCP
          {{- range $index, $val := .Values.localstack.services }}
            - name: {{ $val.name }}
              containerPort: {{ $val.internalPort }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: USE_SSL
              value: !!string {{ .Values.localstack.useSsl }}
            - name: SERVICES
              value: "{{- range $index, $val := .Values.localstack.services -}}
                      {{- if $index -}},{{- end -}}{{- $val.name -}}:{{- $val.internalPort -}}
                      {{- end -}}"
            {{- $root :=  . -}}
            {{- with .Values.localstack }}
              {{- if .defaultRegion }}
            - name: DEFAULT_REGION
              value: {{ .defaultRegion | quote}}
              {{- end }}
            - name: HOST_EXTERNAL
              {{- if .hostExternal }}
              value: {{.hostExternal | quote}}
              {{- else }}
              value: "{{- template "localstack.fullname" $root -}}.{{- $root.Release.Namespace -}}"
              {{- end }}
              {{- if .kinesisErrorProbability }}
            - name: KINESIS_ERROR_PROBABILITY
              value: {{.kinesisErrorProbability | quote}}
              {{- end }}
              {{- if .dynamodbErrorProbability }}
            - name: DYNAMODB_ERROR_PROBABILITY
              value: {{.dynamodbErrorProbability | quote}}
              {{- end }}
              {{- if .lambdaExecutor }}
            - name: LAMBDA_EXECUTOR
              value: {{.lambdaExecutor | quote }}
              {{- end }}
              {{- range $key, $val := .services -}}
              {{- if $val.enabled  }}
              {{- if $val.endpoint  }}
            - name: {{$val.name | upper}}_BACKEND
              value: {{$val.endpoint | quote}}
              {{- end }}
              {{- end }}
              {{- end -}}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: DATA_DIR
              value: "/tmp/localstack/data"
            {{- end }}
            - name: PORT_WEB_UI
              value: {{ .Values.localstack.port | quote }}
          # @todo ensure correct
          # {{- if .Values.persistence.mounts }}
          # {{ toYaml .Values.persistence.mounts | indent 12 }}
          # {{- end }}
          volumeMounts:
            - name: datadir
              mountPath: /tmp/localstack
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      # @todo ensure correct
      volumes:
        - name: datadir
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "localstack.fullname" .)}}
      {{- else }}
          emptyDir: {}
      {{- end }}
