name: AWS / MA/MR tests

on:
  schedule:
    - cron: 0 1 * * MON-FRI
  pull_request:
    paths:
      - '.github/workflows/aws-tests-mamr.yml'
  workflow_dispatch:
    inputs:
      disableCaching:
        description: 'Disable Caching'
        required: false
        type: boolean
        default: false
      PYTEST_LOGLEVEL:
        type: choice
        description: Loglevel for PyTest
        options:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
          - CRITICAL
        default: WARNING

env:
  IMAGE_NAME: "localstack/localstack"
  TINYBIRD_DATASOURCE: "community_tests_circleci_ma_mr"

jobs:
  test-ma-mr:
    name: Run integration tests
    uses: ./.github/workflows/aws-tests.yml
    env:
      TEST_AWS_REGION_NAME: "us-east-2"
      TEST_AWS_ACCOUNT_ID: "00000000004"
      TEST_AWS_ACCESS_KEY_ID: "00000000004"
    with:
      disableCaching: ${{ inputs.disableCaching == true }}
      PYTEST_LOGLEVEL: ${{ inputs.PYTEST_LOGLEVEL }}
      randomize-aws-credentials: true
