name: Open marker report GH issue
on:
  # only manual for now
  workflow_dispatch:
  pull_request:  # TODO: remove before merge
    branches:
      - master

jobs:
  marker-report-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache LocalStack community dependencies (venv)
        uses: actions/cache@v3
        with:
          path: .venv
          # we can re-use the venv from other actions, but shouldn't write one that may be used by others since we install additional deps
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('setup.cfg') }}-marker-report-issue
          restore-keys: |
            ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('setup.cfg') }}

      - name: Install dependencies
        run: make install-dev

        # makes use of the marker report plugin localstack.testing.pytest.marker_report
      - name: Generate marker report
        env:
          PYTEST_ADDOPTS: "-p no:localstack.testing.pytest.fixtures -p no:localstack.testing.pytest.snapshot -p no:localstack.testing.pytest.filters -p no:localstack.testing.pytest.fixture_conflicts -p no:tests.fixtures -s --co --disable-warnings --marker-report --marker-report-path './target'"
          MARKER_REPORT_PROJECT_NAME: localstack
          MARKER_REPORT_COMMIT_SHA: ${{ github.sha }}
        run: |
          . ./.venv/bin/activate
          pip install codeowners
          python -m pytest tests/
          mv ./target/marker-report*.json ./target/marker-report.json

      - name: Enrich and render marker report
        env:
          MARKER_REPORT_PATH: ./target/marker-report.json
          CODEOWNERS_PATH: ./CODEOWNERS
          TEMPLATE_PATH: ./.github/bot_templates/MARKER_REPORT_ISSUE.md.j2
          OUTPUT_PATH: ./target/MARKER_REPORT_ISSUE.md
          GITHUB_REPO: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          . ./.venv/bin/activate
          pip install codeowners
          python scripts/render_marker_report.py

      - name: Print generated markdown
        run: |
          cat ./target/MARKER_REPORT_ISSUE.md

      - name: Upload generated markdown
        uses: actions/upload-artifact@v3
        with:
          path: ./target/MARKER_REPORT_ISSUE.md

# TODO: enable before merge
#      - name: Create GH issue from template
#        uses: JasonEtco/create-an-issue@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          update_existing: true
#          search_existing: all
#          filename: .github/bot_templates/MARKER_REPORT_ISSUE.md
