name: Enforce no major on main

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, synchronize]
    # only enforce for PRs targeting the main branch
    branches:
    - main

jobs:
  enforce-no-major:
    permissions:
      issues: write
      pull-requests: write
    uses: localstack/meta/.github/workflows/pr-enforce-no-major.yml@main
    secrets:
      github-token: ${{ secrets.PRO_ACCESS_TOKEN }}
