name: Enforce Docs Labels

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-docs-labels:
    uses: localstack/meta/.github/workflows/pr-enforce-docs-labels.yml@main
    secrets:
      github-token: ${{ secrets.PRO_ACCESS_TOKEN }}
