on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Terraform Tests
jobs:

  prepare_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(python tests/terraform/get-tf-services.py --names)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test_service:
    needs: prepare_list
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.prepare_list.outputs.matrix) }}
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DNS_ADDRESS: 0
      AWS_DEFAULT_REGION: us-east-2
      AWS_ALTERNATE_REGION: eu-west-1

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Checkout Localstack
      uses: actions/checkout@v3

    # FIXME: pinned because of https://github.com/hashicorp/terraform-provider-aws/issues/27049
    - name: Install terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.9
        terraform_wrapper: false

    - name: Check Terraform version
      run: |
        which terraform
        terraform --version

    - name: Checkout Terraform AWS Provider
      uses: actions/checkout@v3
      with:
        repository: hashicorp/terraform-provider-aws
        path: './terraform-provider-aws'

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'

    - name: Cache Python .venv
      id: python-cache
      uses: actions/cache@v2
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/setup.cfg') }}

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install libsasl2-dev -y
        pip install --upgrade pip
        pip install pyyaml

    - name: Get list of tests for this service
      id: get-list
      run: echo "::set-output name=testlist::$(python tests/terraform/get-tf-tests.py ${{ matrix.service }})"

    - name: Check Test Lists
      if: ${{ steps.get-list.outputs.testlist == '' }}
      run: exit 1

    - name: Installing dependencies and start LocalStack
      run: |
        make install
        make start &

    - name: Patch Terraform Provider
      run: |
        cd terraform-provider-aws
        git apply ../etc/tf-patch/0001-endpoints.patch

    - name: Cache Go dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/terraform-provider-aws/go.sum') }}

    - name: Run Test Cases
      env:
        CI: true
      run: |
        bash tests/terraform/run.sh ${{ matrix.service }} ${{ steps.get-list.outputs.testlist }}
