name: Update test durations

on:
  schedule:
    - cron: 0 4 * 1-12 MON
  workflow_dispatch:
    inputs:
      publishMethod:
        description: 'Select how to publish the workflow result'
        type: choice
        options:
          - UPLOAD_ARTIFACT
          - CREATE_PR
        default: UPLOAD_ARTIFACT

env:
  # Take test durations only for this platform
  PLATFORM: "amd64"
permissions:
  actions: read
  contents: write

jobs:
  update:
    uses: localstack/meta/.github/workflows/update-test-durations.yml@update-test-durations-action
    with:
      repo: localstack/localstack
      workflowName: "AWS / Build, Test, Push"
      branch: main
      eventFilter: schedule
      platform: amd64
      outPath: .test_durations
      publishMethod: ${{ inputs.publishMethod }}
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
      # pr-token: ${{ secrets.PRO_ACCESS_TOKEN }}  # optional; omit to use GITHUB_TOKEN
