name: LocalStack - Validate Codeowners

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate codeowners
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "files,duppatterns,syntax"
          experimental_checks: "avoid-shadowing"
